nlp_engine_name: spacy
models:
  - lang_code: en
    model_name: en_core_web_sm
  - lang_code: ru
    model_name: ru_core_news_lg

ner_model_configuration:
  model_to_presidio_entity_mapping:
    PER: PERSON
    PERSON: PERSON
    NORP: NRP
    FAC: LOCATION
    LOC: LOCATION
    GPE: LOCATION
    LOCATION: LOCATION
    ORG: ORGANIZATION
    ORGANIZATION: ORGANIZATION
    DATE: DATE_TIME
    TIME: DATE_TIME

    # Добавляем маппинг для кастомных распознавателей из файла default_recognizers.yaml
    ID_NUMBER: ID_NUMBER         # Паспорт, СНИЛС, ИНН, водительское удостоверение и т.д.
    PHONE_NUMBER: PHONE_NUMBER   # Номера телефонов
    EMAIL: EMAIL_ADDRESS         # Электронные почты
    LOCATION: ADDRESS            # Адреса проживания
    CREDIT_CARD: CREDIT_CARD     # Кредитные карты
    BANK_ACCOUNT: BANK_ACCOUNT   # Банковские реквизиты
    MEDICAL: MEDICAL_DATA        # Медицинские данные
    FINANCE: INCOME_DATA         # Данные о доходах и налогах

  low_confidence_score_multiplier: 0.4
  low_score_entity_names:
  - 
  labels_to_ignore:
  - ORGANIZATION  # Many false positives
  - CARDINAL
  - EVENT
  - LANGUAGE
  - LAW
  - MONEY
  - ORDINAL
  - PERCENT
  - PRODUCT
  - QUANTITY
  - WORK_OF_ART
  - LOC  # Много ложных срабатываний в русском языке
  - NORP
